require("dotenv-flow").config({ default_node_env: "development" });

module.exports = {
  NODE_ENV: process.env.NODE_ENV || "development",
  HOST: process.env.HOST || "localhost",
  PORT: process.env.PORT || 8080,
  CORS_ORIGIN: process.env.CORS_ORIGIN || "http://localhost:5002",
  API_KEY: process.env.API_KEY,
  AUTH_DOMAIN: process.env.AUTH_DOMAIN,
  PROJECT_ID: process.env.PROJECT_ID,
  STORAGE_BUCKET: process.env.STORAGE_BUCKET,
  MESSAGING_SENDER_ID: process.env.MESSAGING_SENDER_ID,
  APP_ID: process.env.APP_ID,
  MEASUREMENT_ID: process.env.MEASUREMENT_ID,
  DB_URL: process.env.DB_URL,
  FB_SVC_ACC_TYPE: process.env.FB_SVC_ACC_TYPE,
  FB_SVC_ACC_PROJECT_ID: process.env.FB_SVC_ACC_PROJECT_ID,
  FB_SVC_ACC_PRIVATE_KEY_ID: process.env.FB_SVC_ACC_PRIVATE_KEY_ID,
  FB_SVC_ACC_PRIVATE_KEY: process.env.FB_SVC_ACC_PRIVATE_KEY.replace(/\n/gm, '\n'),
  FB_SVC_ACC_CLIENT_EMAIL: process.env.FB_SVC_ACC_CLIENT_EMAIL,
  FB_SVC_ACC_CLIENT_ID: process.env.FB_SVC_ACC_CLIENT_ID,
  FB_SVC_ACC_AUTH_URI: process.env.FB_SVC_ACC_AUTH_URI,
  FB_SVC_ACC_TOKEN_URI: process.env.FB_SVC_ACC_TOKEN_URI,
  FB_SVC_ACC_AUTH_PROVIDER_X509_CERT_URL: process.env.FB_SVC_ACC_AUTH_PROVIDER_X509_CERT_URL,
  FB_SVC_ACC_CLIENT_X509_CERT_URL: process.env.FB_SVC_ACC_CLIENT_X509_CERT_URL,
};
